# Generated by Django 2.0 on 2017-12-12 22:24

import bora.models
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bora', '0005_auto_20171212_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='full_image',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='artwork',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='', upload_to=bora.models.user_gallery_path),
            preserve_default=False,
        ),
    ]
