# Generated by Django 2.0 on 2017-12-17 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bora', '0007_auto_20171217_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bora.Rank'),
        ),
    ]
