# Generated by Django 2.0 on 2017-12-17 17:07

import bora.models
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bora', '0008_user_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='user',
            name='aliik',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=bora.models.aliiki),
        ),
        migrations.AlterField(
            model_name='user',
            name='art_name',
            field=models.TextField(blank=True, null=True, verbose_name='Art name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='op_name',
            field=models.TextField(blank=True, null=True, verbose_name='Operation name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bora.Rank'),
        ),
        migrations.AlterField(
            model_name='user',
            name='story',
            field=models.TextField(blank=True, null=True, verbose_name='Story'),
        ),
    ]
