# Generated by Django 2.0 on 2017-12-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bora', '0009_auto_20171217_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='art_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Art name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='anon', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='op_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Operation name'),
        ),
    ]
