# Generated by Django 2.0 on 2017-12-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bora', '0010_auto_20171217_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
