# Generated by Django 2.0 on 2017-12-17 18:13

import bora.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bora', '0011_auto_20171217_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('introduction', models.TextField(verbose_name='Introduction')),
                ('ending', models.TextField(verbose_name='Ending')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('views', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=bora.models.aliiki)),
                ('report', models.TextField(blank=True, null=True, verbose_name='Report')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bora.Event')),
            ],
        ),
    ]
