# Generated by Django 2.0 on 2017-12-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bora', '0013_auto_20171218_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewitem',
            name='org_title',
            field=models.CharField(max_length=255, verbose_name='Orginal Title'),
        ),
    ]
