# Generated by Django 2.0 on 2017-12-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bora', '0014_auto_20171218_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewitem',
            name='translator',
            field=models.CharField(max_length=255, null=True, verbose_name='Translator'),
        ),
    ]
